# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  #- job_name: 'flask_app'
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: ['localhost:8000']

  - job_name: 'cloudwatch_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9106']

  - job_name: 'prom_ptyhon_app'
    static_configs:
      - targets: ['localhost:8001']

  - job_name: 'consul_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9107']

  - job_name: 'consul'
    consul_sd_configs:
      - server:   '127.0.0.1:8500'

    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         ',(dev|production|canary),'
      target_label:  'group'
      replacement:   '$1'

